name : SmartBaby
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: 0.13.6
  intl: ^0.18.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0
  wakelock_plus: ^1.1.3
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_charts: ^25.1.35
  flutter_locales: ^3.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.8




  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  dialog_flowtter: ^0.3.3
  rxdart: ^0.27.7
  bootstrap_icons: ^1.11.3
  web_socket_channel: ^2.4.4
  firebase_messaging: ^14.8.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  fl_chart: ^0.67.0



    #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/application/
    - assets/dialog_flow_auth.json
    - assets/application/
  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800