// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vypYH2mG6nO2JJFl66gOgNnygnaQonA',
    appId: '1:487451931248:web:1bcbdf1919050af491bab5',
    messagingSenderId: '487451931248',
    projectId: 'bebemonietur',
    authDomain: 'bebemonietur.firebaseapp.com',
    storageBucket: 'bebemonietur.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqYKx9zmc8OfO0viza2Nk3T4sLxz47yQU',
    appId: '1:487451931248:android:f2d432de40bbb73a91bab5',
    messagingSenderId: '487451931248',
    projectId: 'bebemonietur',
    storageBucket: 'bebemonietur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9otx4SD5KhmA3TYHKmfaMn2WFu1jWPFs',
    appId: '1:487451931248:ios:bb0dd10da65901e291bab5',
    messagingSenderId: '487451931248',
    projectId: 'bebemonietur',
    storageBucket: 'bebemonietur.appspot.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );
}
